version: "3"
services:
  eureka-server:
    container_name: eureka-server
    ports:
      - "9010:9010"
    image: amazoncorretto:11
    volumes:
      - ./eureka-server:/app
    working_dir: /app
    entrypoint: ./gradlew --no-daemon --stacktrace bootRun

  gateway:
    container_name: gateway
    ports:
      - "9000:9000"
    image: amazoncorretto:11
    volumes:
      - ./gateway:/app
    working_dir: /app
    environment:
      EUREKA_SERVER: eureka-server
    entrypoint: ./gradlew --no-daemon --stacktrace bootRun

  healthy-service:
    container_name: healthy-service
    ports:
      - "9001:9001"
    image: amazoncorretto:11
    volumes:
      - ./healthy-service:/app
    working_dir: /app
    environment:
      EUREKA_SERVER: eureka-server
    entrypoint: ./gradlew --no-daemon --stacktrace bootRun

  faulty-service:
    container_name: faulty-service
    ports:
      - "9002:9002"
    image: amazoncorretto:11
    volumes:
      - ./faulty-service:/app
    working_dir: /app
    environment:
      EUREKA_SERVER: eureka-server
    entrypoint: ./gradlew --no-daemon --stacktrace bootRun

  slow-service:
    container_name: slow-service
    ports:
      - "9003:9003"
    image: amazoncorretto:11
    volumes:
      - ./slow-service:/app
    working_dir: /app
    environment:
      EUREKA_SERVER: eureka-server
    entrypoint: ./gradlew --no-daemon --stacktrace bootRun
