version: "3"
services:
  eureka-server:
    container_name: eureka-server
    ports:
      - "9010:9010"
    image: openjdk:8-jdk-alpine
    volumes:
      - ./eureka-server:/app
    working_dir: /app
    entrypoint: ./gradlew bootRun

  gateway:
    container_name: gateway
    ports:
      - "9000:9000"
    image: openjdk:8-jdk-alpine
    volumes:
      - ./gateway:/app
    working_dir: /app
    entrypoint: ./gradlew bootRun

  health-service:
    container_name: health-service
    ports:
      - "9001:9001"
    image: openjdk:8-jdk-alpine
    volumes:
      - ./gateway:/app
    working_dir: /app
    entrypoint: ./gradlew bootRun

  faulty-service:
    container_name: faulty-service
    ports:
      - "9002:9002"
    image: openjdk:8-jdk-alpine
    volumes:
      - ./gateway:/app
    working_dir: /app
    entrypoint: ./gradlew bootRun

  slow-service:
    container_name: slow-service
    ports:
      - "9003:9003"
    image: openjdk:8-jdk-alpine
    volumes:
      - ./gateway:/app
    working_dir: /app
    entrypoint: ./gradlew bootRun
