server:
  port: 9001

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:9010/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: healthy-service
