server:
  port: ${PORT:9000}

spring:
  application:
    name: gateway
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
        - id: healthy-service
          uri: lb://healthy-service
          predicates:
            - Path=/healthy/**
          filters:
            - RewritePath=/healthy/(?<path>.*), /$\{path}
            # The `CircuitBreaker` filter is enabled via spring-cloud-starter-circuitbreaker-reactor-resilience4j
            # https://cloud.spring.io/spring-cloud-gateway/reference/html/#spring-cloud-circuitbreaker-filter-factory
            - name: CircuitBreaker
              args:
                # The `name` value is passed to Resilience4JConfigBuilder as `id`
                # SEE: DemoConfiguration#defaultCustomizer
                name: healthyService

logging.level.io.github.resilience4j: DEBUG

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:9010/eureka/
  instance:
    preferIpAddress: true