server:
  port: ${PORT:9000}

spring:
  application:
    name: gateway-service
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://localhost:9001
          predicates:
            - Path=/item/**
          filters:
            - RewritePath=/item/(?<path>.*), /$\{path}
            # The `CircuitBreaker` filter is enabled via spring-cloud-starter-circuitbreaker-reactor-resilience4j
            # https://cloud.spring.io/spring-cloud-gateway/reference/html/#spring-cloud-circuitbreaker-filter-factory
            - name: CircuitBreaker
              args:
                # The `name` value is passed to Resilience4JConfigBuilder as `id`
                # SEE: DemoConfiguration#defaultCustomizer
                name: exampleSlowCircuitBreaker

logging.level.io.github.resilience4j: DEBUG