server:
  port: 9003

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:9010/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: slow-service